### ISSUE TITLE
Not currently available for KNIME 5.x

### ISSUE THREAD

**Issue by sroughley** [3D-e-Chem/knime-testflow#10]
I am updating the Vernalis KNIME community contribution (and hopefully eventually internal nodes) for KNIME 5.x (5.0, 5.1) but we have dependencies on this project for testflow execution.  Do you have plans to update to allow KNIME 5.x compatibility?

Many thanks,

Steve

**Comment by sverhoeven** [comment]
Hi Steve,  
Did not know it was being used. Great to hear that you are using it.

I tried to upgrade to KNIME 5 in #11, but got stuck on

```bash
mvn verify
[INFO] Scanning for projects...
[INFO] Computing target platform for MavenProject: nl.esciencecenter.e3dchem.knime.testing:nl.esciencecenter.e3dchem.knime.testing.plugin:1.0.3-SNAPSHOT @ /home/verhoes/git/knime-testflow/plugin/pom.xml
[INFO] Adding repository https://update.knime.org/analytics-platform/5.0
[INFO] Fetching p2.index from https://update.knime.org/analytics-platform/5.0/5.0.0/ (116B)
[INFO] Fetching p2.index from https://update.knime.org/analytics-platform/5.0/5.0.1/ (116B)
[INFO] Fetching p2.index from https://update.knime.org/analytics-platform/5.0/5.0.1/ (116B)
[ERROR] Failed to resolve target definition /home/verhoes/git/knime-testflow/targetplatform/KNIME-AP-4.0.target: Could not find "org.knime.features.testingapplication.feature.group/0.0.0" in the repositories of the current location -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
```

If you could help resolve the errors then I could make a new release of this repo that supports KNIME 5.

**Comment by sroughley** [comment]
Hi Sven,

Thanks for looking into this.  I'm not really sure where to start unpicking that dependency requirement right now.  I'm going to highlight that back in the email thread with the KNIME people to see what they think (and also try having a look at it myself), but we also need some way where there is a version accessible which runs on KNIME 4.x in addition to a KNIME 5.x version too.  I can't actually see how the update site is deployed (I assume, perhaps wrongly!) github actions.

**Comment by steffen-fissler** [comment]
Hi @sverhoeven , the testing application feature has a new name since few versions ago, it is now "org.knime.features.testing.application.feature.group", note the extra dot between "testing" and "application"

best regards,
Steffen

**Comment by sroughley** [comment]
Thanks @steffen-fissler - I have a version locally which now gets some way further.  With either KNIME 4.7 or KNIME 5.1 I now have the following error during `mvn clean verify -B` :

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.7.5:compile (default-compile) on project nl.esciencecenter.e3dchem.knime.testing.plugin: Compilation failure: Compilation failure:
[ERROR] C:\git\knime-testflow\plugin\src\java\nl\esciencecenter\e3dchem\knime\testing\core\ng\WorkflowLoadTest.java:[124]
[ERROR]         public WorkflowContext getWorkflowContext() {
[ERROR]                ^^^^^^^^^^^^^^^
[ERROR] The return type is incompatible with WorkflowLoadHelper.getWorkflowContext()
[ERROR] C:\git\knime-testflow\plugin\src\java\nl\esciencecenter\e3dchem\knime\testing\core\ng\WorkflowExecuteTest.java:[131]
[ERROR]         message += "\nThread status:\n" + GUIDeadlockDetector.createStacktrace();
[ERROR]                                                               ^^^^^^^^^^^^^^^^
[ERROR] The method createStacktrace() is undefined for the type GUIDeadlockDetector
[ERROR] 2 problems (2 errors)
```

I know there have been some changes in the KNIME core around `WorkflowContext` so I assume this might be related to those - I will keep investigating!

(I'm actually wondering if this is also the source of this sort of output in out internal builds using this framework:
```
WARN 	 main WorkflowManager	 No workflow context available for null
java.lang.Throwable
	at org.knime.core.node.workflow.WorkflowManager.<init>(WorkflowManager.java:546)
	at org.knime.core.node.workflow.WorkflowManager.createSubWorkflow(WorkflowManager.java:1170)
	at org.knime.core.node.workflow.FileWorkflowPersistor.getNodeContainer(FileWorkflowPersistor.java:338)
	at org.knime.core.node.workflow.WorkflowManager.loadNodesAndConnections(WorkflowManager.java:8886)
	at org.knime.core.node.workflow.WorkflowManager.loadContent(WorkflowManager.java:8591)
	at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:8464)
	at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:8385)
	at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:8358)
	at org.knime.core.node.workflow.WorkflowManager.loadProject(WorkflowManager.java:8202)
	at nl.esciencecenter.e3dchem.knime.testing.core.ng.WorkflowLoadTest.loadWorkflow(WorkflowLoadTest.java:131)
	at nl.esciencecenter.e3dchem.knime.testing.core.ng.WorkflowLoadTest.run(WorkflowLoadTest.java:110)
	at nl.esciencecenter.e3dchem.knime.testing.TestFlowRunner.runTestWorkflow(TestFlowRunner.java:94)
	at com.vernalis.internal.testing.AbstractWorkflowTest.runTestFlow(AbstractWorkflowTest.java:276)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:206)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:161)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:84)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:128)
	at org.eclipse.tycho.surefire.osgibooter.HeadlessTestApplication.start(HeadlessTestApplication.java:23)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```
but that is possibly a different issue altogether!)

(Incidentally, my version builds OK with JDK-1.8 / KNIME-4.0, but the tests fail because of this issue - https://www.eclipse.org/forums/index.php/t/1089060/ because I am running JDK17!)

**Comment by sroughley** [comment]
As a further update:

I have now fixed these 2 errors:

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.7.5:compile (default-compile) on project nl.esciencecenter.e3dchem.knime.testing.plugin: Compilation failure: Compilation failure:
[ERROR] C:\git\knime-testflow\plugin\src\java\nl\esciencecenter\e3dchem\knime\testing\core\ng\WorkflowLoadTest.java:[124]
[ERROR]         public WorkflowContext getWorkflowContext() {
[ERROR]                ^^^^^^^^^^^^^^^
[ERROR] The return type is incompatible with WorkflowLoadHelper.getWorkflowContext()
[ERROR] C:\git\knime-testflow\plugin\src\java\nl\esciencecenter\e3dchem\knime\testing\core\ng\WorkflowExecuteTest.java:[131]
[ERROR]         message += "\nThread status:\n" + GUIDeadlockDetector.createStacktrace();
[ERROR]                                                               ^^^^^^^^^^^^^^^^
[ERROR] The method createStacktrace() is undefined for the type GUIDeadlockDetector
[ERROR] 2 problems (2 errors)
```
The first is a result of the migration to `WorkflowContextV2` in KNIME 4.7 onwards, the second a result of this change back in KNIME 4.1 - https://github.com/knime/knime-core/commit/431217bb1568a39625946b753bb993459f0f2604

I have some test failures to disentangle but I think this is headed now in the right direction
