### ISSUE TITLE
Incompatible with KNIME 3.3

### ISSUE THREAD

**Issue by sverhoeven** [3D-e-Chem/knime-testflow#4]
Using https://github.com/3D-e-Chem/tycho-knime-node-archetype with knime_version=3.3 running the `mvn verify` gave the following error:
```
[INFO] test_simple(foo.bar.knime.somenode.SomeNodeWorkflowTest)  Time elapsed: 1.627 sec  <<< ERROR!
[INFO] java.lang.NoSuchMethodError: org.knime.core.node.workflow.WorkflowContext$Factory.setMountpointRoot(Ljava/io/File;)V
[INFO] 	at nl.esciencecenter.e3dchem.knime.testing.core.ng.WorkflowLoadTest$1.getWorkflowContext(WorkflowLoadTest.java:115)
[INFO] 	at org.knime.core.node.workflow.FileWorkflowPersistor.getWorkflowContext(FileWorkflowPersistor.java:470)
[INFO] 	at org.knime.core.node.workflow.WorkflowManager.<init>(WorkflowManager.java:493)
[INFO] 	at org.knime.core.node.workflow.WorkflowManager.createSubWorkflow(WorkflowManager.java:876)
[INFO] 	at org.knime.core.node.workflow.FileWorkflowPersistor.getNodeContainer(FileWorkflowPersistor.java:398)
[INFO] 	at org.knime.core.node.workflow.WorkflowManager.loadNodesAndConnections(WorkflowManager.java:7953)
[INFO] 	at org.knime.core.node.workflow.WorkflowManager.loadContent(WorkflowManager.java:7657)
[INFO] 	at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:7619)
[INFO] 	at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:7543)
[INFO] 	at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:7516)
[INFO] 	at org.knime.core.node.workflow.WorkflowManager.loadProject(WorkflowManager.java:7365)
[INFO] 	at nl.esciencecenter.e3dchem.knime.testing.core.ng.WorkflowLoadTest.loadWorkflow(WorkflowLoadTest.java:120)
[INFO] 	at nl.esciencecenter.e3dchem.knime.testing.core.ng.WorkflowLoadTest.run(WorkflowLoadTest.java:99)
[INFO] 	at nl.esciencecenter.e3dchem.knime.testing.TestFlowRunner.runTestWorkflow(TestFlowRunner.java:96)
[INFO] 	at foo.bar.knime.somenode.SomeNodeWorkflowTest.test_simple(SomeNodeWorkflowTest.java:37)

```

**Comment by sverhoeven** [comment]
Also the TestRunConfiguration now has saveloadsave enabled by default. Causing an exception because  the nl.esciencecenter.e3dchem.knime.testing.plugin does not have it implemented.

A workaround is to disable it with `runConfiguration.setLoadSaveLoad(false);`.

**Comment by sverhoeven** [comment]
KNIME 4 is out, which works OK. 

Upgrade to KNIME 4, will not fix issues for older KNIME versions.
